name: hospital_microgrid
description: Smart Hospital Microgrid with Self-Learning Energy Management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart: ^0.66.0
  google_fonts: ^6.1.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.5.0
  shared_preferences: ^2.2.2
  printing: ^5.13.0
  share_plus: ^10.0.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

